In [62]:
import pandas as pd
import numpy as np
import tensorflow as tf
from sklearn.preprocessing import MinMaxScaler
from sklearn.model_selection import train_test_split

stock_df = pd.read_csv('indexData.csv')
stock_df

Index        Date         Open         High          Low        Close  \
0        NYA  1965-12-31   528.690002   528.690002   528.690002   528.690002   
1        NYA  1966-01-03   527.210022   527.210022   527.210022   527.210022   
2        NYA  1966-01-04   527.840027   527.840027   527.840027   527.840027   
3        NYA  1966-01-05   531.119995   531.119995   531.119995   531.119995   
4        NYA  1966-01-06   532.070007   532.070007   532.070007   532.070007   
...      ...         ...          ...          ...          ...          ...   
112452  N100  2021-05-27  1241.119995  1251.910034  1241.119995  1247.069946   
112453  N100  2021-05-28  1249.469971  1259.209961  1249.030029  1256.599976   
112454  N100  2021-05-31  1256.079956  1258.880005  1248.140015  1248.930054   
112455  N100  2021-06-01  1254.609985  1265.660034  1254.609985  1258.579956   
112456  N100  2021-06-02  1258.489990  1263.709961  1258.239990  1263.619995   

          Adj Close       Volume  
0        528.690002          0.0  
1        527.210022          0.0  
2        527.840027          0.0  
3        531.119995          0.0  
4        532.070007          0.0  
...             ...          ...  
112452  1247.069946  379696400.0  
112453  1256.599976  160773400.0  
112454  1248.930054   91173700.0  
112455  1258.579956  155179900.0  
112456  1263.619995  148465000.0  

[112457 rows x 8 columns]

### Data preprocessing

In [81]:
stock_NYA_df = stock_df[stock_df['Index'] == 'NYA']
stock_NYA_df

Index        Date          Open          High           Low  \
0       NYA  1965-12-31    528.690002    528.690002    528.690002   
1       NYA  1966-01-03    527.210022    527.210022    527.210022   
2       NYA  1966-01-04    527.840027    527.840027    527.840027   
3       NYA  1966-01-05    531.119995    531.119995    531.119995   
4       NYA  1966-01-06    532.070007    532.070007    532.070007   
...     ...         ...           ...           ...           ...   
13943   NYA  2021-05-24  16375.000000  16508.519530  16375.000000   
13944   NYA  2021-05-25  16464.689450  16525.810550  16375.150390   
13945   NYA  2021-05-26  16390.189450  16466.339840  16388.320310   
13946   NYA  2021-05-27  16451.960940  16546.359380  16451.960940   
13947   NYA  2021-05-28  16531.949220  16588.689450  16531.949220   

              Close     Adj Close        Volume  
0        528.690002    528.690002  0.000000e+00  
1        527.210022    527.210022  0.000000e+00  
2        527.840027    527.840027  0.000000e+00  
3        531.119995    531.119995  0.000000e+00  
4        532.070007    532.070007  0.000000e+00  
...             ...           ...           ...  
13943  16464.689450  16464.689450  2.947400e+09  
13944  16390.189450  16390.189450  3.420870e+09  
13945  16451.960940  16451.960940  3.674490e+09  
13946  16531.949220  16531.949220  5.201110e+09  
13947  16555.660160  16555.660160  4.199270e+09  

[13948 rows x 8 columns]

In [82]:
stock_NYA_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13948 entries, 0 to 13947
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Index      13948 non-null  object 
 1   Date       13948 non-null  object 
 2   Open       13947 non-null  float64
 3   High       13947 non-null  float64
 4   Low        13947 non-null  float64
 5   Close      13947 non-null  float64
 6   Adj Close  13947 non-null  float64
 7   Volume     13947 non-null  float64
dtypes: float64(6), object(2)
memory usage: 980.7+ KB


In [83]:
stock_NYA_df = stock_NYA_df.dropna()
stock_NYA_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13947 entries, 0 to 13947
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   Index      13947 non-null  object 
 1   Date       13947 non-null  object 
 2   Open       13947 non-null  float64
 3   High       13947 non-null  float64
 4   Low        13947 non-null  float64
 5   Close      13947 non-null  float64
 6   Adj Close  13947 non-null  float64
 7   Volume     13947 non-null  float64
dtypes: float64(6), object(2)
memory usage: 980.6+ KB


In [84]:
stock_NYA_df['Date'] = pd.to_datetime(stock_NYA_df['Date'])
stock_NYA_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 13947 entries, 0 to 13947
Data columns (total 8 columns):
 #   Column     Non-Null Count  Dtype         
---  ------     --------------  -----         
 0   Index      13947 non-null  object        
 1   Date       13947 non-null  datetime64[ns]
 2   Open       13947 non-null  float64       
 3   High       13947 non-null  float64       
 4   Low        13947 non-null  float64       
 5   Close      13947 non-null  float64       
 6   Adj Close  13947 non-null  float64       
 7   Volume     13947 non-null  float64       
dtypes: datetime64[ns](1), float64(6), object(1)
memory usage: 980.6+ KB


/tmp/ipykernel_19509/3815177697.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_NYA_df['Date'] = pd.to_datetime(stock_NYA_df['Date'])


In [85]:
stock_NYA_df['day_difference'] = stock_NYA_df['Date'].diff().dt.days
stock_NYA_df

/tmp/ipykernel_19509/761583660.py:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  stock_NYA_df['day_difference'] = stock_NYA_df['Date'].diff().dt.days


Index       Date          Open          High           Low  \
0       NYA 1965-12-31    528.690002    528.690002    528.690002   
1       NYA 1966-01-03    527.210022    527.210022    527.210022   
2       NYA 1966-01-04    527.840027    527.840027    527.840027   
3       NYA 1966-01-05    531.119995    531.119995    531.119995   
4       NYA 1966-01-06    532.070007    532.070007    532.070007   
...     ...        ...           ...           ...           ...   
13943   NYA 2021-05-24  16375.000000  16508.519530  16375.000000   
13944   NYA 2021-05-25  16464.689450  16525.810550  16375.150390   
13945   NYA 2021-05-26  16390.189450  16466.339840  16388.320310   
13946   NYA 2021-05-27  16451.960940  16546.359380  16451.960940   
13947   NYA 2021-05-28  16531.949220  16588.689450  16531.949220   

              Close     Adj Close        Volume  day_difference  
0        528.690002    528.690002  0.000000e+00             NaN  
1        527.210022    527.210022  0.000000e+00             3.0  
2        527.840027    527.840027  0.000000e+00             1.0  
3        531.119995    531.119995  0.000000e+00             1.0  
4        532.070007    532.070007  0.000000e+00             1.0  
...             ...           ...           ...             ...  
13943  16464.689450  16464.689450  2.947400e+09             3.0  
13944  16390.189450  16390.189450  3.420870e+09             1.0  
13945  16451.960940  16451.960940  3.674490e+09             1.0  
13946  16531.949220  16531.949220  5.201110e+09             1.0  
13947  16555.660160  16555.660160  4.199270e+09             1.0  

[13947 rows x 9 columns]

In [86]:
stock_NYA_df['day_difference'].value_counts()

day_difference
1.0    10889
3.0     2556
4.0      332
2.0      165
5.0        3
7.0        1
Name: count, dtype: int64

In [87]:
data = stock_NYA_df['Adj Close'].to_numpy()
data

array([  528.690002,   527.210022,   527.840027, ..., 16451.96094 ,
       16531.94922 , 16555.66016 ])

In [88]:
data.shape

(13947,)

In [89]:
data = np.reshape(data, (len(data), 1))
data.shape

(13947, 1)

In [90]:
data

array([[  528.690002],
       [  527.210022],
       [  527.840027],
       ...,
       [16451.96094 ],
       [16531.94922 ],
       [16555.66016 ]])

In [91]:
scaler = MinMaxScaler()
scaled_data = scaler.fit_transform(data)
scaled_data

array([[0.01113857],
       [0.01104745],
       [0.01108624],
       ...,
       [0.991475  ],
       [0.99639958],
       [0.99785937]])

In [92]:
window_size = 60

X, y = [], []

for i in range(window_size, len(scaled_data)):
    X.append(scaled_data[i-window_size:i, 0])
    y.append(scaled_data[i, 0])

X[:2]

[array([0.01113857, 0.01104745, 0.01108624, 0.01128818, 0.01134666,
        0.01137929, 0.01145748, 0.01148334, 0.01142486, 0.01149012,
        0.01155476, 0.01167851, 0.01176962, 0.01169143, 0.0115683 ,
        0.01158739, 0.01169143, 0.01171791, 0.01168528, 0.01167235,
        0.0115683 , 0.01142486, 0.01116443, 0.01130788, 0.01134666,
        0.01155476, 0.01166558, 0.01163972, 0.01182811, 0.01173699,
        0.01173084, 0.01169821, 0.01155476, 0.0115486 , 0.01137252,
        0.01130788, 0.0111121 , 0.01096926, 0.0107544 , 0.01084551,
        0.0108843 , 0.01047427, 0.01016213, 0.01029203, 0.01019414,
        0.00976503, 0.00979704, 0.01005747, 0.01006424, 0.01003838,
        0.00967391, 0.0094652 , 0.00963451, 0.0097324 , 0.009882  ,
        0.01012273, 0.01021384, 0.0101098 , 0.01015536, 0.01023355]),
 array([0.01104745, 0.01108624, 0.01128818, 0.01134666, 0.01137929,
        0.01145748, 0.01148334, 0.01142486, 0.01149012, 0.01155476,
        0.01167851, 0.01176962, 0.01169143, 0.

In [93]:
X, y = np.array(X), np.array(y)
X[:2]

array([[0.01113857, 0.01104745, 0.01108624, 0.01128818, 0.01134666,
        0.01137929, 0.01145748, 0.01148334, 0.01142486, 0.01149012,
        0.01155476, 0.01167851, 0.01176962, 0.01169143, 0.0115683 ,
        0.01158739, 0.01169143, 0.01171791, 0.01168528, 0.01167235,
        0.0115683 , 0.01142486, 0.01116443, 0.01130788, 0.01134666,
        0.01155476, 0.01166558, 0.01163972, 0.01182811, 0.01173699,
        0.01173084, 0.01169821, 0.01155476, 0.0115486 , 0.01137252,
        0.01130788, 0.0111121 , 0.01096926, 0.0107544 , 0.01084551,
        0.0108843 , 0.01047427, 0.01016213, 0.01029203, 0.01019414,
        0.00976503, 0.00979704, 0.01005747, 0.01006424, 0.01003838,
        0.00967391, 0.0094652 , 0.00963451, 0.0097324 , 0.009882  ,
        0.01012273, 0.01021384, 0.0101098 , 0.01015536, 0.01023355],
       [0.01104745, 0.01108624, 0.01128818, 0.01134666, 0.01137929,
        0.01145748, 0.01148334, 0.01142486, 0.01149012, 0.01155476,
        0.01167851, 0.01176962, 0.01169143, 0.0

In [94]:
X.shape

(13887, 60)

In [95]:
test_split = 0.2
split_index = int(len(y) * (1-test_split))
X_train = X[:split_index]
Y_train = y[:split_index]
X_test = X[(split_index + window_size - 1):]
Y_test = y[(split_index + window_size - 1):]

indices = np.arange(len(Y_train))
np.random.shuffle(indices)
X_train = X_train[indices]
Y_train = Y_train[indices]

In [96]:
X_train[:2]

array([[0.51434066, 0.51646836, 0.5172983 , 0.52011123, 0.52316249,
        0.51913297, 0.51832707, 0.51883193, 0.51533245, 0.51560523,
        0.5152475 , 0.52158023, 0.52254064, 0.52391542, 0.52121762,
        0.52209494, 0.52184868, 0.52532651, 0.52662433, 0.5261891 ,
        0.52635468, 0.52555432, 0.52764204, 0.529542  , 0.52858706,
        0.52163993, 0.52355155, 0.52943299, 0.53077699, 0.52954999,
        0.53385717, 0.53668302, 0.53562593, 0.53527012, 0.53528305,
        0.53666829, 0.53633395, 0.53774197, 0.54174811, 0.54132881,
        0.53915307, 0.54127037, 0.5406202 , 0.53905459, 0.53651065,
        0.53898069, 0.54373056, 0.54332172, 0.54124446, 0.54087879,
        0.53965239, 0.53422717, 0.53521716, 0.534157  , 0.53287764,
        0.53656975, 0.54130115, 0.54127771, 0.54169021, 0.54040472],
       [0.11726836, 0.11523729, 0.11492514, 0.11543245, 0.11409831,
        0.11371414, 0.11449541, 0.11413709, 0.11383111, 0.11571936,
        0.11565409, 0.11538074, 0.11461916, 0.1

### Creating a model

In [97]:
model_lstm = tf.keras.models.Sequential()
model_lstm.add(tf.keras.layers.LSTM(units=50, return_sequences=True, input_shape=(X_train.shape[1], 1), recurrent_dropout=0.2))
model_lstm.add(tf.keras.layers.LSTM(units=50))
model_lstm.add(tf.keras.layers.Dense(units=1))

# optimizer = tf.keras.optimizers.Adam(learning_rate=0.001, clipvalue=1.0)
model_lstm.compile(optimizer='Adam', loss='mean_squared_error', metrics=['mae'])
model_lstm.summary()

Model: "sequential_12"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 lstm_21 (LSTM)              (None, 60, 50)            10400     
                                                                 
 lstm_22 (LSTM)              (None, 50)                20200     
                                                                 
 dense_11 (Dense)            (None, 1)                 51        
                                                                 
Total params: 30651 (119.73 KB)
Trainable params: 30651 (119.73 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


### Traning a model

In [98]:
model_lstm.fit(X_train, Y_train, epochs=30, batch_size=32, validation_split=0.2)

Epoch 1/30
278/278 [==============================] - 16s 46ms/step - loss: 8.8792e-04 - mae: 0.0103 - val_loss: 3.7368e-05 - val_mae: 0.0034
Epoch 2/30
278/278 [==============================] - 12s 43ms/step - loss: 5.1301e-05 - mae: 0.0041 - val_loss: 3.5705e-05 - val_mae: 0.0034
Epoch 3/30
278/278 [==============================] - 12s 43ms/step - loss: 4.4957e-05 - mae: 0.0038 - val_loss: 3.3370e-05 - val_mae: 0.0035
Epoch 4/30
278/278 [==============================] - 12s 43ms/step - loss: 4.3163e-05 - mae: 0.0039 - val_loss: 3.1320e-05 - val_mae: 0.0032
Epoch 5/30
278/278 [==============================] - 12s 43ms/step - loss: 4.3388e-05 - mae: 0.0039 - val_loss: 3.0026e-05 - val_mae: 0.0030
Epoch 6/30
278/278 [==============================] - 12s 43ms/step - loss: 4.0002e-05 - mae: 0.0038 - val_loss: 4.2349e-05 - val_mae: 0.0041
Epoch 7/30
278/278 [==============================] - 12s 43ms/step - loss: 3.7274e-05 - mae: 0.0037 - val_loss: 3.1429e-05 - val_mae: 0.0032
Epoch 

KeyboardInterrupt: 